services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
        volumes:
            - ./storage:/var/www/html/storage
            - ./bootstrap/cache:/var/www/html/bootstrap/cache
            - ./database:/var/www/html/database
        networks:
            - laravel_network
        mem_limit: 512m
        cpus: 0.7
        healthcheck:
            test: ["CMD", "php", "-v"]
            timeout: 10s
            retries: 5
            start_period: 20s

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            app:
                condition: service_healthy
        networks:
            - laravel_network
        mem_limit: 64m

networks:
    laravel_network:
        driver: bridge
