services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
        volumes:
            - ./storage:/var/www/html/storage
            - ./bootstrap/cache:/var/www/html/bootstrap/cache
            - ./database:/var/www/html/database
            - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./docker/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
        networks:
            - laravel_network
        mem_limit: 512m
        cpus: 0.7
        healthcheck:
            test: ["CMD", "php", "-v"]
            timeout: 10s
            retries: 5
            start_period: 30s

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
            - certbot_certs:/etc/letsencrypt
            - certbot_www:/var/www/certbot
        depends_on:
            app:
                condition: service_healthy
        networks:
            - laravel_network
        mem_limit: 64m
        healthcheck:
            test: ["CMD", "nginx", "-t"]
            timeout: 10s
            retries: 3

    certbot:
        image: certbot/certbot
        container_name: laravel_certbot
        volumes:
            - certbot_certs:/etc/letsencrypt
            - certbot_www:/var/www/certbot
        command: >
            sh -c "
            if [ ! -f /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem ]; then
                certbot certonly --webroot --webroot-path=/var/www/certbot
                --email ${SSL_EMAIL} --agree-tos --no-eff-email
                -d ${DOMAIN_NAME} --non-interactive
            else
                echo 'Certificate already exists'
            fi
            "
        depends_on:
            - nginx
        profiles:
            - ssl

volumes:
    certbot_certs:
    certbot_www:

networks:
    laravel_network:
        driver: bridge
