version: '3.8'

services:
  app:
    image: ghcr.io/ferdikam/groupify:latest
    container_name: laravel-app-green
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - laravel_storage_data:/app/storage
      - ./logs:/app/storage/logs
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://yourdomain.com
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=${DB_PASSWORD}
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  laravel_storage_data:
    external: true

networks:
  laravel:
    external: true
